services:
  - type: web
    name: my-website
    env: static
    staticPublishPath: dist
    routes:
      - source: /model/.*   # Serve all files in the /model directory
        headers:
          Content-Type: application/octet-stream
